import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const alignCenter = { display: 'flex', alignItems: 'center' }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
      <Parallax pages={5}>
        <ParallaxLayer offset={0} speed={0.5} style={{ ...alignCenter, justifyContent: 'center' }}>
          <p>layer 0</p>
        </ParallaxLayer>

        <ParallaxLayer sticky={{ start: 1, end: 3 }} className='flex items-center justify-start border'>
          <div className={`flex justify-center h-[10rem] w-1/4 text-center rounded-md ml-[15%] bg-amber-300`}>
            <p>layer 1</p>
          </div>
        </ParallaxLayer>

        <ParallaxLayer offset={1.5} speed={1.5} className='flex items-center justify-end border'>
          <div className={`flex justify-center h-[10rem] w-1/4 text-center rounded-md mr-[15%] bg-purple-400`}>
            <p>layer 2</p>
          </div>
        </ParallaxLayer>

        <ParallaxLayer offset={2.5} speed={1.5} className='flex items-center justify-end border'>
          <div className={`flex justify-center h-[10rem] w-1/4 text-center rounded-md mr-[15%] bg-purple-400`}>
            <p>layer 3</p>
          </div>
        </ParallaxLayer>
      </Parallax>
      </main>
    </>
  )
}
