import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { Parallax, ParallaxLayer } from '@react-spring/parallax'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const alignCenter = { display: 'flex', alignItems: 'center' }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
      <Parallax pages={6}>
        <ParallaxLayer offset={0} speed={0.5} style={{ ...alignCenter, justifyContent: 'center' }}>
          <p>layer 0</p>
        </ParallaxLayer>

        <ParallaxLayer sticky={{ start: 1, end: 4 }} speed={0.5} className='parallax-layer'>
          <div className={`card bg-amber-300`}>
            <p>layer 1</p>
          </div>
        </ParallaxLayer>

        <ParallaxLayer sticky={{ start: 2, end: 4 }} speed={0.5} className='parallax-layer'>
          <div className={`card bg-purple-400`}>
            <p>layer 2</p>
          </div>
        </ParallaxLayer>

        <ParallaxLayer sticky={{ start: 3, end: 4 }} speed={0.5} className='parallax-layer'>
          <div className={`card bg-blue-400`}>
            <p>layer 3</p>
          </div>
        </ParallaxLayer>
      </Parallax>
      </main>
    </>
  )
}
