import Img from '@/components/Img'
import React from 'react';
import Image from "next/image";
import {
  motion,
  useScroll,
  useSpring,
  useTransform,
  MotionValue,
} from "framer-motion";
import img from "../public/carImg.jpg";
import Parallax from '@/components/Parallax'
// import ExplosiveHeader from '@/components/exposiveHeader'
// import PointerBlur from '@/components/pointerBlur'
import Head from 'next/head'
// import Image from 'next/image'

function useParallax(value: MotionValue<number>, distance: number) {
  return useTransform(value, [0, 1], [-distance, distance]);
}

function Container({ id }: { id: number }) {
  const ref = React.useRef(null);
  const { scrollYProgress } = useScroll({ target: ref });
  const y = useParallax(scrollYProgress, 300);

  return (
    <div className="flex h-full w-full aid items-center justify-items-center relative text-center snap-center">
      <div
        ref={ref}
        className="relative snap-center mx-auto w-80 h-[500px] m-6 overflow-hidden "
      >
        <Image
          src={img}
          alt="img"
          className="absoulte border border-sky-400 top-0 left-0 w-full h-full right-0 bottom-0 rounded"
          placeholder="blur"
        />
      </div>
      <motion.h2
        className="text-white text-4xl absolute"
        style={{ y }}
      >
        {`#00${id}`}
      </motion.h2>
    </div>
  );
}


export default function Home() {
  const { scrollYProgress } = useScroll();
  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001,
  });


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* w-screen h-screen min-h-fit flex items-center justify-center overflow-scroll */}
      <main className='w-full h-screen  snap-y snap-mandatory'>
        {/* <PointerBlur/> */}
        {/* <ExplosiveHeader title='TESTING'/> */}
        {/* <Img/> */}
        {/* <Parallax/> */}
        {[1, 2, 3, 4, 5].map((num: number) => (
          <Container key={num} id={num} />
        ))}
        <motion.div
          className="fixed bg-white rounded left-0 right-0 h-2 bottom-14"
          style={{ scaleX }}
        />
      </main>
    </>
  )
}
