import ExplosiveHeader from '@/components/exposiveHeader'
import PointerBlur from '@/components/pointerBlur'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-screen h-screen flex items-center justify-center overflow-hidden'>
        {/* <PointerBlur/> */}
        <ExplosiveHeader title='Testing'/>
      </main>
    </>
  )
}
